name: agricola
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.12+22

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  agricola_core:
    git:
      url: https://github.com/agricola-dev/agricola-core.git
      ref: main
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.3.0
  intl: ^0.20.2
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.1
  fpdart: ^1.2.0
  equatable: ^2.0.8
  dio: ^5.9.0
  firebase_storage: ^13.0.6
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_crashlytics: ^5.0.8
  firebase_analytics: ^12.1.3
  feedback: ^3.2.0
  flutter_email_sender: ^8.0.0
  package_info_plus: ^9.0.0
  drift: ^2.22.1
  drift_flutter: ^0.2.4
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  csv: ^6.0.0
  pdf: ^3.11.0
  share_plus: ^10.0.0
  shimmer: ^3.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  drift_dev: ^2.22.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
