class BotswanaLocations {
  static const List<String> settlements = [
    // Gaborone & surrounds
    'Gaborone',
    'Mogoditshane',
    'Tlokweng',
    'Ramotswa',
    'Gabane',
    'Mmopone',
    'Kopong',
    'Odi',
    'Gakuto',
    // Kgatleng District
    'Mochudi',
    'Artesia',
    'Bokaa',
    'Leshibitse',
    'Malolwane',
    'Oodi',
    'Pilane',
    'Mmathubudukwane',
    'Morwa',
    // Kweneng District
    'Molepolole',
    'Thamaga',
    'Lentsweletau',
    'Mmankgodi',
    'Ntlhantlhe',
    'Letlhakeng',
    'Motokwe',
    'Ngware',
    'Shadishadi',
    'Sojwe',
    'Takatokwane',
    'Medie',
    'Nnywane',
    'Lotlhakane',
    // Southern District
    'Kanye',
    'Lobatse',
    'Moshupa',
    'Goodhope',
    'Sesung',
    'Phitshane Molopo',
    'Manyana',
    'Ranaka',
    'Moshaneng',
    'Mmathethe',
    'Digawana',
    'Otse',
    'Lefhoko',
    'Khakhea',
    'Sekoma',
    'Mabutsane',
    'Kang',
    'Hukuntsi',
    'Tshane',
    'Lokgwabe',
    'Lehututu',
    'Werda',
    'Mabule',
    'Struizendam',
    // Central District
    'Serowe',
    'Palapye',
    'Mahalapye',
    'Letlhakane',
    'Orapa',
    'Bobonong',
    'Lerala',
    'Mmadinare',
    'Sefhare',
    'Sefophe',
    'Tonota',
    'Marobela',
    'Tsetsebjwe',
    'Shoshong',
    'Taupye',
    'Mookane',
    'Mmashoro',
    'Chadibe',
    'Nkange',
    'Lepashe',
    'Ramokgonami',
    'Rakops',
    'Mopipi',
    'Kumaga',
    'Machaneng',
    'Mogapi',
    'Mogapinyana',
    'Serule',
    'Dibete',
    'Pilikwe',
    'Radisele',
    'Mokubilo',
    'Molalatau',
    'Khumaga',
    'Selebi-Phikwe',
    'Jwaneng',
    'Sowa Town',
    // Northeast District
    'Francistown',
    'Masunga',
    'Nata',
    'Gweta',
    'Tutume',
    'Dukwi',
    'Shashe Mooke',
    'Jackalas',
    'Tati Siding',
    'Matshelagabedi',
    'Kalakamati',
    'Mathangwane',
    // Chobe District
    'Kasane',
    'Kavimba',
    'Kachikau',
    'Satau',
    'Mabele',
    'Lesoma',
    'Pandamatenga',
    'Kazungula',
    'Ngoma',
    // Ngamiland District (Northwest)
    'Maun',
    'Shakawe',
    'Gumare',
    'Etsha 6',
    'Etsha 13',
    'Nokaneng',
    'Sehithwa',
    'Toteng',
    'Shorobe',
    'Sepupa',
    'Seronga',
    'Beetsha',
    'Ngarange',
    'Mohembo',
    'Samochima',
    'Nxamasere',
    'Eretsha',
    'Tobere',
    'Habu',
    'Tsodilo',
    'Guma',
    // Ghanzi District
    'Ghanzi',
    'Kalkfontein',
    'Charles Hill',
    'Chobokwane',
    'D\'Kar',
    'Bere',
    'Ncojane',
    'Tshootsha',
    'Dekar',
    // Kgalagadi District
    'Tsabong',
    'Middlepits',
    'Bokspits',
    'Ukhwi',
    'Two Rivers',
    'Hunhukwe',
    'Zutshwa',
    'Khawa',
  ];

  // Returns matches ordered: startsWith first, then contains.
  static List<String> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return [];
    final starts = <String>[];
    final contains = <String>[];
    for (final s in settlements) {
      final lower = s.toLowerCase();
      if (lower.startsWith(q)) {
        starts.add(s);
      } else if (lower.contains(q)) {
        contains.add(s);
      }
    }
    return [...starts, ...contains];
  }
}
